// Code generated by goctl. DO NOT EDIT.
package types

type CommonPagination struct {
	Page     uint32 `json:"page,optional,default=1"`      // 页码
	PageSize uint32 `json:"pageSize,optional,default=10"` // 每页数量
}

type DemoListItem struct {
	ID          string `json:"id"`
	Name        string `json:"name"`          // name
	Sex         uint8  `json:"sex"`           // 性别 1男 2女 3保密
	DateOfBirth string `json:"date_of_birth"` // 生日
	Avatar      string `json:"avatar"`        // 头像
	Email       string `json:"email"`         // email
	Phone       string `json:"phone"`         // 手机号
}

type DemoAddReq struct {
	Name        string `json:"name"`          // name
	Sex         uint8  `json:"sex"`           // 性别 1男 2女 3保密
	DateOfBirth string `json:"date_of_birth"` // 生日
	Avatar      string `json:"avatar"`        // 头像
	Email       string `json:"email"`         // email
	Phone       string `json:"phone"`         // 手机号
}

type DemoAddRes struct {
	ID string `json:"id"`
}

type DemoDelReq struct {
	ID string `json:"id"`
}

type DemoDelRes struct {
}

type DemoListReq struct {
	CommonPagination
	Name string `form:"name,optional"` // name
}

type DemoListRes struct {
	Total uint32          `json:"total"` // 总数
	Items []*DemoListItem `json:"items"`
}

type DemoUpdateReq struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type DemoUpdateRes struct {
}
